name: cquizy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder: ^10.2.0
  form_builder_validators: ^11.2.0
  wave: ^0.2.2
  http: ^1.5.0
  flutter_slidable: ^3.1.0
  provider: ^6.1.5+1
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  loading_animation_widget: ^1.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true

  assets:
    - assets/logo/logo_2.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo_2.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/logo/logo_2.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/logo/logo_2.png"
    icon_size: 48
